# vim: set noexpandtab ts=4:
#
# Authors: PA
# Maintainers:
# Copyright: 2023, HRDAG, GPL v2 or later
# ----------------------------------------------------------
# CO-examples/Resultados-CEV/Makefile

HERE := $(shell git rev-parse --show-toplevel)

.PHONY: clean all

all: \
	output/reclutamiento-anio-estratificacion.html	\
	output/reclutamiento-anio-estimacion.html	\
	output/secuestro-anio-estratificacion.html	\
	output/secuestro-anio-estimacion.html \
	output/homicidio-anio-estratificacion.html	\
	output/homicidio-anio-estimacion.html	

clean:
	rm output/*

output/homicidio-anio-estratificacion.html: \
		src/homicidio-anio-estratificacion.Rmd
	-mkdir output
		Rscript -e "rmarkdown::render('$<')"

output/homicidio-anio-estimacion.html: \
		src/homicidio-anio-estimacion.Rmd
	-mkdir output
		Rscript -e "rmarkdown::render('$<')"

output/reclutamiento-anio-estratificacion.html: \
		src/reclutamiento-anio-estratificacion.Rmd
	-mkdir output
		Rscript -e "rmarkdown::render('$<')"

output/reclutamiento-anio-estimacion.html: \
		src/reclutamiento-anio-estimacion.Rmd
	-mkdir output
		Rscript -e "rmarkdown::render('$<')"

output/secuestro-anio-estratificacion.html: \
		src/secuestro-anio-estratificacion.Rmd
	-mkdir output
		Rscript -e "rmarkdown::render('$<')"

output/secuestro-anio-estimacion.html: \
		src/secuestro-anio-estimacion.Rmd
	-mkdir output
		Rscript -e "rmarkdown::render('$<')"

# Done