---
title: "Introduction to the data examples from the JEP-CEV-HRDAG joint project"
output:
  rmdformats::robobook:
    code_folding: show
    self_contained: true
    thumbnails: false
    lightbox: true
    gallery: true
    use_bookdown: true
    highlight: kate
    embed_fonts: false
knit: (function(inputFile, encoding) {rmarkdown::render(inputFile, encoding = encoding, output_dir = "../output") })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction {-}

The examples in this repository illustrate how to reproduce some of the findings about documented, imputed, and estimated victims of human rights abuses during the armed conflict in Colombia analyzed in the JEP-CEV-HRDAG joint project. These examples make use of the `R` package [`verdata`](https://github.com/HRDAG/verdata), a tool designed to facilitate working with this data. The `verdata` package consists of the following functions: `confirm_files`, `read_replicates`, `filter_standard_cev`, `summary_observed`, `combine_replicates`, `mse`, and `combine_estimates`. These examples demonstrate how these functions should be used and introduces a workflow for their use.

## What should we have in mind before using the package? {-}

Before you begin to work with the data, it is important to define a few concepts. These concepts will help you replicate the calculations done in the [methodological report of the joint project](https://hrdag.org/wp-content/uploads/2022/08/20220818-fase4-informe-corrected.pdf) (English translation coming soon) and the statistics presented in the [Final Report of the Truth Commission](https://www.comisiondelaverdad.co/hay-futuro-si-hay-verdad). Additionally, they are important to understand for users interested in designing their own analyses about the armed conflict in Colombia.

To introduce these concepts, it is important to remember that the project was divided into three phases: the integration of data sources (record linkage), the statistical imputation of missing field values, and the estimation of underreporting (see the [methodological report](https://hrdag.org/wp-content/uploads/2022/08/20220818-fase4-informe-corrected.pdf) for more information about each phase). The sections that follow offer a brief summary of the key concepts from each of these phases.
 
**A. Observed data**

The observed data refer to victims' whose information was documented in the integrated database, the database that was created after combining and de-duplicating the records from more than 100 databases provided by numerous institutions in Colombia. Not all victims documented in the integrated database had complete information such as their sex, age, or information about the perpetrator presumed to have committed the human rights abuse, among other fields. For the victims where this information was missing, there is uncertainty about how these missing fields should be filled in.   

**B. Imputed fields**

We used a statistical method called multiple imputation to address the issue of missing information in the documented records. This method allows us to generate multiple versions of the integrated database with the missing information filled in showing the *possible* values that fields such as the age and ethnicity of the victim or the presumed perpetrator of the abuse among others. We call these observations imputed fields or imputed data (statistically speaking; this should not to be confused with imputation in legal terms). We repeated the process of statistically imputing the missing fields in documented records 100 times, or replicates, for each human rights violation. You can think of each replicate as a different version of the data. For example, if the record of Victim 1 did not have information about their ethnicity, the imputation model may have assigned the value to Indigenous in Replicate 1, mestizo in Replicate 2, Indigenous again in Replicate 3, etc. Let's assume that at the end of the process, we observe that the imputation model assigned the victim's ethnicity to Indigenous 54 times, mestizo 30 times, and NARP (Black, Afro-Colombian, Raizales, and Palenqueras) 16 times. We are not sure of the real ethnicity of this victim because it was not documented, however, we observe the most likely value according to the imputation model. In this case, the most probable value for this missing field is Indigenous (see the [methodological report](https://hrdag.org/wp-content/uploads/2022/08/20220818-fase4-informe-corrected.pdf) for more information about this model).

**C. Estimation of underreporting**

While many victims were documented in the integrated database, it's important to remember that none of the databases included in the joint project nor the integrated database document *all* conflict victims. There are still victims' whose stories have not been documented by any of the data sources included in the project, what we refer to as underreporting or underdocumentation. We use another statistical model called multiple systems estimation to address this underreporting (see the [methodological report](https://hrdag.org/wp-content/uploads/2022/08/20220818-fase4-informe-corrected.pdf) for more information).

## Conclusion {-}

<!-- done. -->